### PR TITLE
Clojure v1.11.1

### LINKED ISSUE #238: Update ClojureDocs to v1.11
I.e. add the `clojure.math` namespace and the following functions to `clojure.core`

\- [abs](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/abs) 
\- [NaN?](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/NaN?)
\- [infinite?](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/infinite?) 
\- [parse-double](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-double) 
\- [parse-long](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-long) 
\- [parse-boolean](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-boolean) 
\- [parse-uuid](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/parse-uuid) 
\- [random-uuid](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/random-uuid) 
\- [update-keys](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/update-keys) 
\- [update-vals](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/update-vals) 
\- [iteration](https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/iteration).

### PR DESCRIPTION
**Pull request by eval**
Fixes #238

### CODE REVIEW

**Comment by eval** [comment]
Local tests worked flawlessly. @zk let me know if this needs more.

**Comment by Crowbrammer** [comment]
Is @zk okay? <:(

**Comment by port19x** [comment]
This repo hasn't seen a single commit in a year...
Should have been transferred to clj-commons or sth before it got abandoned

**Comment by eval** [comment]
To move this under clj-commons would be great I think. Would you be open to explore the options @zk ?

**Comment by zk** [comment]
Thanks @eval! To answer your question, I'm not interested in moving this to clj commons at this time.

**Comment by zk** [comment]
Quick update, working through some issues getting this deployed. More context here: https://github.com/zk/clojuredocs/blob/master/.notes.zk.org#2023-07-24-mon-1036

**Comment by eval** [comment]
Thanks for the update! 🙏🏻

**Pull request merged**
