### PR TITLE
remove the nsfw library

### PR DESCRIPTION
**Pull request by dimmyjr**
### Proposal

Remove the **nsfw** library to avoid transitive dependencies like congomongo and then bump all dependencies.

**changes on this pr**

- remove the nsfw library
- copy the util and other namespace from nsfw to the project
- switch the pegdown to flexmark-all (pegdown is DEPRECATED)
- apply linters and reorganize importas as intellij suggestions
- upgrade the congomongo to 2.6.0 for support new release mongodb

**next steps**

- bump dependencies

> My idea in the future is to add support for other libraries to clojuredocs. So that the community can also contribute examples and notes to relevant libraries.

### CODE REVIEW

**Comment by dimmyjr** [comment]
Hi @zk 

could you review this PR please, and check if it makes sense?

**Comment by NoahTheDuke** [comment]
As an outsider, this seems like a bunch of unrelated and unnecessary changes alongside the goal of removing the nsfw library (which you don't include any reasoning for). Maybe start with an issue first?

**Comment by NoahTheDuke** [comment]
Sure, but you've described multiple steps. Breaking them down into individual PRs will 1) reduce the cognitive load to review (+1,786, −226 is big enough that I would reject out of hand if this was an out of the blue PR on one of my projects), and 2) make it possible to check your work at each stage (are there subtle bugs introduced? Easier to find that out when the change set is small), and 3) allow time for considering the further changes by themselves, so zk can pick and choose which parts he wants to incorporate (instead of the all or nothing in a single commit PR).

**Comment by NoahTheDuke** [comment]
To be specific, "In the future, I would like to add support for other libs and because of the dependencies this is a problem." is something you want from clojuredocs, but is that what zk wants from clojuredocs? Have you talked to him about it? Have you talked to community at large about it? What alternatives have you considered?

**Pull request closed without merging**
