### PR TITLE
Updated to Clojure 1.10.1

### PR DESCRIPTION
**Pull request by ilyabe**
For issue https://github.com/zk/clojuredocs/issues/198
Now we have the new vars and namespaces added in Clojure 1.10.1. Done just as described under [clojure-version](https://github.com/zk/clojuredocs#clojure-version). Also added some of the namespaces listed uner #198.

### CODE REVIEW

**Comment by zk** [comment]
Thanks Ilya. 

What's this look like with the new namespaces in the sidebar? Everything work correctly on chrome / firefox / safari desktop & mobile?

Please revert changes to the project desc and version.

**Comment by ilyabe** [comment]
No thanks needed! Actually, thank you for making this quite handy app _and_ documenting how to update it.

The namespaces in the sidebar scroll now. Should we make it taller so it doesn't or what do you think?

image

I'll also test some more on the browsers and make sure all looks OK and revert the description and version, no problem.

**Comment by zk** [comment]
Looks good, yeah, nesting v scrollers isn’t ideal but it works 🤷‍♂️.

I’m more worried about horizontal though, iirc we’ve had issues in the past
with longer namespaces being cut off or wrapping.

**Comment by ilyabe** [comment]
Looks good in Chrome, Safari, Firefox desktop & mobile, and didn't see any namespaces cut off. I noticed that I hadn't updated the Clojure version in the mobile nav, so that's updated too now, and I added a note about that in the `README`.
image

**Comment by zk** [comment]
Good catch on the mobile nav. I'll verify on my local later today and get it shipped if everything looks good. Thanks!

**Comment by zk** [comment]
Ok, started to take a look but I'm blocked by https://github.com/technomancy/leiningen/issues/2513 atm. Going to be a bit before I can get to this.

**Comment by ilyabe** [comment]
Awww man, sorry... That's funny, I used to work with the reporter of that issue :-) Hey @vincentstorme did you ever get it solved?

**Comment by zk** [comment]
Whoops, 'blocked' was a poor choice of words. Looks like there are solutions (bump dependencies or downgrade lein), it's just I've got a pretty busy week and don't want to roll the dice on messing with my environment.

**Comment by vincentstorme** [comment]
@ilyabe hey! Yeah I reported that ages ago.

@zk up easiest solution I found was to downgrade lein at that tkme, though I think all current versions of everything work together now

**Comment by ilyabe** [comment]
@vincentstorme Yeah, I remember you fighting with that!
@zk No worries, take your time, Clojuredocs with 1.9 is still awesome!

**Pull request merged**
