### PR TITLE
remove the nsfw to avoid transitive deps like congomongo and bump it.

### PR DESCRIPTION
**Pull request by dimmyjr**
Hi Zach 

As we agreed in the conversation via zoom on 10/19/2023. Follow some of the first PR's

Taking advantage, I would also like to mention that we will prioritize the feature for external reading of the namespace so that it is no longer necessary to read it at run-time, making it possible to support other libraries

### Scope of this PR

The "nsfw" library has been removed to eliminate transitive dependencies and possibly bump the "congomongo". Now, it is possible to connect Clojuredocs with new versions of MongoDB while still supporting the old versions.

**MongoDB and Congomongo:**
We conducted exploratory tests using MongoDB 5 and 7, and they performed well in our tests, which included CRUD tests in "examples", "see also", and "notes". We recommend keeping the database in its current version, as the updated library (congomongo) has no compatibility issues.

> in parts of the code where "ObjectId." It was necessary to add "(str)" because this function implicitly requires "String"

**nsfw**
nsfw introduced some dependencies like congomongo. To streamline our dependencies, we made the decision to remove nsfw and extract the necessary namespace from it, such as:

- nsfw.reup
- nsfw.css
- nsfw.util
- nsfw.ops
- nsfw.page

**Pegdown**
We replaced Pegdown with Flexmark-All, as Pegdown is now deprecate and caused some issues with other dependencies.

### CODE REVIEW

**Comment by zk** [comment]
Hey @dimmyjr appreciate the work here. Will get the clojuredocs server image updated to mongo 7 and ready for deployment with the updated dependencies.

**Comment by zk** [comment]
Fantastic, thanks @dimmyjr

**Comment by zk** [comment]
Deployed

**Comment by eval** [comment]
Great to see that this unlocked the release 🙏🏻

**Comment by dimmyjr** [comment]
Nice @zk 🤘

Thank you!

**Pull request merged**
